apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: backend-container
        image: medicalreviewacr5641343725980c14.azurecr.io/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: DB_SERVER
          value: "medicalreview-sqlserver-5641343725980c14.database.windows.net"
        - name: DB_DATABASE
          value: "MedicalReview-DB"
        - name: DB_USER
          value: "sqladmin"
        - name: DB_PASSWORD
          value: "Password1234!"
        - name: AZURE_LANGUAGE_ENDPOINT
          value: "https://southeastasia.api.cognitive.microsoft.com/"
        - name: AZURE_LANGUAGE_KEY
          value: "ae84a4fcc423459a845002def1c19a67"
        - name: APPINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=f665c474-d0c7-4494-87c2-6ff08741d0e1;IngestionEndpoint=https://southeastasia-1.in.applicationinsights.azure.com/;LiveEndpoint=https://southeastasia.livediagnostics.monitor.azure.com/;ApplicationId=30ce64c7-e891-41c3-b903-5b8e1a72180b"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
