apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: backend-container
        image: medicalreviewacrc728ea6834a6c4ef.azurecr.io/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: DB_SERVER
          value: "medicalreview-sqlserver-c728ea6834a6c4ef.database.windows.net"
        - name: DB_DATABASE
          value: "MedicalReview-DB"
        - name: DB_USER
          value: "sqladmin"
        - name: DB_PASSWORD
          value: "Password1234!"
        - name: AZURE_LANGUAGE_ENDPOINT
          value: "https://southeastasia.api.cognitive.microsoft.com/"
        - name: AZURE_LANGUAGE_KEY
          value: "ddd1888eb7224652892c9e629d6bb414"
        - name: APPINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=60374f13-50f7-4d95-a8c3-ed2c6e520fb9;IngestionEndpoint=https://southeastasia-1.in.applicationinsights.azure.com/;LiveEndpoint=https://southeastasia.livediagnostics.monitor.azure.com/;ApplicationId=c1037fdc-176e-4537-9e0a-d78839e25048"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
